### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by HeartMath-Brandon** [filippotoso/driver-rocket-chat#3]
Is there a way you would be able to update the Setup Instructions? I got a key to put in the config but I seem to be missing a couple of steps.  Like the endpoint url. Also, how do I add this to a bot that is already setup?

**Comment by filippotoso** [comment]
> I seem to be missing a couple of steps. Like the endpoint url.

As specified in the configuration file, in the endpoint field you have to specify the url of your Rocket Chat Server. This base url will be used for the REST API calls: https://rocket.chat/docs/developer-guides/rest-api/

```php
    /**
     * Rocket Chat Base URL
     *
     * The url your Rocket Chat server answers to (used for API calls)
     */
```

> Also, how do I add this to a bot that is already setup?

Also in the documentation:

> Then load the driver before creating the BotMan instance (only when you don't use BotMan Studio):

```php
DriverManager::loadDriver(\FilippoToso\BotMan\Drivers\RocketChat\RocketChatDriver::class);

// Create BotMan instance
BotManFactory::create($config);
```

If you are using BotMan Studio, the driver is automatically loaded as all the other drivers.

**Comment by Avalarion** [comment]
And in RocketChat the Url is `https://myBotMan.site/botman`, correct?

**Comment by filippotoso** [comment]
If you are using Botman Studio, yes, that's the route: https://github.com/botman/studio/blob/master/routes/web.php
Otherwise it's the route you defined.
